# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest' # Web Deploy (msdeploy) requires a Windows agent

variables:
  # Path to the UI project to be built and deployed
  uiProjectPath: 'src/TravelAppUI/TravelAppUI.csproj'
  # Path to the API project
  apiProjectPath: 'src/Api/Api.csproj'

  # Build configuration
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: 'Build_Api'
    displayName: 'Build and publish API'
    pool:
      vmImage: 'windows-latest'
    steps:
    # The project files indicate .NET 9. This task ensures the correct SDK is available.
    - task: UseDotNet@2
      displayName: 'Use .NET 9.x SDK'
      inputs:
        packageType: 'sdk'
        version: '9.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore Api dependencies'
      inputs:
        command: 'restore'
        projects: '$(apiProjectPath)'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: 'Build Api project'
      inputs:
        command: 'build'
        projects: '$(apiProjectPath)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Api project'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(apiProjectPath)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)\publish'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\publish'
        ArtifactName: 'api-app'
        publishLocation: 'Container'
  - job: 'Build_UI'
    displayName: 'Build and publish UI'
    pool:
      vmImage: 'windows-latest'
    steps:
    # The project files indicate .NET 9. This task ensures the correct SDK is available.
    - task: UseDotNet@2
      displayName: 'Use .NET 9.x SDK'
      inputs:
        packageType: 'sdk'
        version: '9.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore UI dependencies'
      inputs:
        command: 'restore'
        projects: '$(uiProjectPath)'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: 'Build UI project'
      inputs:
        command: 'build'
        projects: '$(uiProjectPath)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish UI project'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(uiProjectPath)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)\publish'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\publish'
        ArtifactName: 'ui-app'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployWebApps
    displayName: 'Deploy Web apps via Web Deploy'
    environment: 'Production_MonsterASP'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download all artifacts from build'
            inputs:
              buildType: 'current'
              downloadType: 'All'
              downloadPath: '$(Pipeline.Workspace)'

          - task: CmdLine@2
            displayName: 'Deploy WEB UI to MonsterASP.NET using Web Deploy'
            inputs:
              script: |
                "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="$(Pipeline.Workspace)\ui-app\TravelAppUI.zip" -dest:contentPath="$(webDeploySiteNameUI)",computerName="$(webDeployServerUI)?site=$(webDeploySiteNameUI)",userName="$(webDeployUsernameUI)",password="$(webDeployPasswordUI)",authtype="Basic",includeAcls="False" -allowUntrusted -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -enableRule:AppOffline -verbose
          - task: CmdLine@2
            displayName: 'Deploy Web API to MonsterASP.NET using Web Deploy'
            inputs:
              script: |
                "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="$(Pipeline.Workspace)\api-app\Api.zip" -dest:contentPath="$(webDeploySiteNameApi)",computerName="$(webDeployServerApi)?site=$(webDeploySiteNameApi)",userName="$(webDeployUsernameApi)",password="$(webDeployPasswordApi)",authtype="Basic",includeAcls="False" -allowUntrusted -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -enableRule:AppOffline -verbose
